#!/bin/sh
# to run this type: curl -sSL https://raw.githubusercontent.com/MartinPred/scripts/refs/heads/main/raspi_docker_setup | sh
set -e

sudo apt update
sudo apt upgrade -y
curl -sSL https://get.docker.com | sh
docker run -d -p 9001:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:latest
